 FastAPI   Starting production server üöÄ
 
             Searching for package file structure from directories with __init__.py files
2025-07-30 23:15:16,117 | INFO | cost_estimator_calc_service | Async SpannerClient initialized for database: projects/anbc-hcb-dev/instances/provider-de/databases/cost-estimator-secure
2025-07-30 23:15:16,117 | INFO | cost_estimator_calc_service | Connection pool size: 10, Max workers: 20
             Importing from /Users/N133723/Desktop/tlabchaat-355-24/cost-estimator-calc-service/app
 
    module   üêç main.py
 
      code   Importing the FastAPI app object from the module with the following code:
 
             from main import app
 
       app   Using import string: main:app
 
    server   Server started at http://0.0.0.0:8000
    server   Documentation at http://0.0.0.0:8000/docs
 
             Logs:
 
      INFO   Will watch for changes in these directories: ['/Users/N133723/Desktop/tlabchaat-355-24/cost-estimator-calc-service']
      INFO   Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
      INFO   Started reloader process [55158] using WatchFiles
2025-07-30 23:15:16,728 | INFO | cost_estimator_calc_service | Async SpannerClient initialized for database: projects/anbc-hcb-dev/instances/provider-de/databases/cost-estimator-secure
2025-07-30 23:15:16,728 | INFO | cost_estimator_calc_service | Connection pool size: 10, Max workers: 20
      INFO   Started server process [55160]
      INFO   Waiting for application startup.
2025-07-30 23:15:16,728 | INFO | cost_estimator_calc_service | Executing async query: SELECT payment_method_cd, score FROM payment_method_hierarchy
2025-07-30 23:15:16,728 | INFO | cost_estimator_calc_service | Query params: None
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
2025-07-30 23:15:19,222 | INFO | cost_estimator_calc_service | Cached payment_method_hierarchy with 42 entries.
      INFO   Application startup complete.
2025-07-30 23:15:39,372 | INFO | cost_estimator_calc_service | Async SpannerClient initialized for database: projects/anbc-hcb-dev/instances/provider-de/databases/cost-estimator-secure
2025-07-30 23:15:39,372 | INFO | cost_estimator_calc_service | Connection pool size: 10, Max workers: 20
benefit_request benefitProductType='Medical' membershipID='5~265642286+34+44+20250101+784461+AM+39' planIdentifier='3~' serviceInfo=[ServiceInfo(serviceCodeInfo=ServiceCodeInfo(providerType=[ProviderType(code='IO')], placeOfService=[PlaceOfService(code='21')], providerSpecialty=[ProviderSpecialty(code=' ')], code='28054', type='CPT4'))]
CostEstimatorRateCriteria fields: {'providerIdentificationNumber': <class 'str'>, 'serviceCode': <class 'str'>, 'serviceType': <class 'str'>, 'serviceLocationNumber': typing.Optional[str], 'networkId': typing.Optional[str], 'placeOfService': <class 'str'>, 'zipCode': <class 'str'>, 'isOutofNetwork': <class 'bool'>, 'providerSpecialtyCode': typing.Optional[str], 'providerType': typing.Optional[str]}
rate_criteria CostEstimatorRateCriteria(providerIdentificationNumber='9394609', serviceCode='28054', serviceType='CPT4', serviceLocationNumber='10701', networkId='12395', placeOfService='21', zipCode='07083', isOutofNetwork=False, providerSpecialtyCode=' ', providerType='IO')
2025-07-30 23:15:39,376 | INFO | cost_estimator_calc_service | Executing async query: SELECT MAX(RATE) AS RATE
FROM CET_CLAIM_BASED_AMOUNTS
WHERE
    PROVIDER_IDENTIFICATION_NBR = @provideridentificationnumber
    AND NETWORK_ID = @networkid
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
2025-07-30 23:15:39,376 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
2025-07-30 23:15:41,406 | INFO | cost_estimator_calc_service | Successfully retrieved new token
2025-07-30 23:15:41,431 | INFO | cost_estimator_calc_service | Successfully retrieved new token
2025-07-30 23:15:41,971 | INFO | cost_estimator_calc_service | Claim-based rate result: [[None]]
2025-07-30 23:15:41,971 | WARNING | cost_estimator_calc_service | Empty or malformed result
2025-07-30 23:15:41,971 | INFO | cost_estimator_calc_service | No claim-based rate found, proceeding to get provider info
2025-07-30 23:15:41,971 | INFO | cost_estimator_calc_service | Missing productcd or providerbusinessgroupnbr; calling _get_provider_info()
2025-07-30 23:15:41,972 | INFO | cost_estimator_calc_service | Executing async query: SELECT DISTINCT PROVIDER_BUSINESS_GROUP_NBR, PRODUCT_CD, RATING_SYSTEM_CD, EPDB_GEOGRAPHIC_AREA_CD
FROM CET_PROVIDERS
WHERE
    PROVIDER_IDENTIFICATION_NBR = @provideridentificationnumber
    AND NETWORK_ID = @networkid
    AND SERVICE_LOCATION_NBR = @servicelocationnumber
2025-07-30 23:15:41,972 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1753935341.981044 2378616 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
2025-07-30 23:15:44,439 | INFO | cost_estimator_calc_service | Provider info result: [['100004781', 'MC', 'REF', 'GN02']]
2025-07-30 23:15:44,439 | INFO | cost_estimator_calc_service | Executing default rate query: SELECT payment_method_cd, RATE
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND PRODUCT_CD = @productcd
    AND PROVIDER_BUSINESS_GROUP_NBR IN UNNEST(@providerbusinessgroupnbr)
    AND CONTRACT_TYPE = 'D' with params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
2025-07-30 23:15:44,439 | INFO | cost_estimator_calc_service | Executing async query: SELECT payment_method_cd, RATE
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND PRODUCT_CD = @productcd
    AND PROVIDER_BUSINESS_GROUP_NBR IN UNNEST(@providerbusinessgroupnbr)
    AND CONTRACT_TYPE = 'D'
2025-07-30 23:15:44,439 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
I0000 00:00:1753935344.443915 2378616 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
2025-07-30 23:15:47,186 | ERROR | cost_estimator_calc_service | Error executing async read-only query: 400 No parameter found for binding: productcd
2025-07-30 23:15:47,186 | ERROR | cost_estimator_calc_service | Query: SELECT payment_method_cd, RATE
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND PRODUCT_CD = @productcd
    AND PROVIDER_BUSINESS_GROUP_NBR IN UNNEST(@providerbusinessgroupnbr)
    AND CONTRACT_TYPE = 'D'
2025-07-30 23:15:47,187 | ERROR | cost_estimator_calc_service | Params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
2025-07-30 23:15:47,187 | ERROR | cost_estimator_calc_service | Exception type: <class 'google.api_core.exceptions.InvalidArgument'>
2025-07-30 23:15:47,187 | ERROR | cost_estimator_calc_service | Exception details: 400 No parameter found for binding: productcd
2025-07-30 23:15:47,187 | INFO | cost_estimator_calc_service | return rows: []
2025-07-30 23:15:47,187 | INFO | cost_estimator_calc_service | No rate rows found for default payment methods
2025-07-30 23:15:47,187 | INFO | cost_estimator_calc_service | Executing async query: SELECT payment_method_cd, RATE
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND PRODUCT_CD = @productcd
    AND PROVIDER_BUSINESS_GROUP_NBR IN UNNEST(@providerbusinessgroupnbr)
    AND CONTRACT_TYPE IN ('C', 'N')
2025-07-30 23:15:47,187 | INFO | cost_estimator_calc_service | Query params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
/Users/N133723/Library/Python/3.12/lib/python/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
I0000 00:00:1753935347.195016 2378616 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
2025-07-30 23:15:49,744 | ERROR | cost_estimator_calc_service | Error executing async read-only query: 400 No parameter found for binding: productcd
2025-07-30 23:15:49,745 | ERROR | cost_estimator_calc_service | Query: SELECT payment_method_cd, RATE
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND PRODUCT_CD = @productcd
    AND PROVIDER_BUSINESS_GROUP_NBR IN UNNEST(@providerbusinessgroupnbr)
    AND CONTRACT_TYPE IN ('C', 'N')
2025-07-30 23:15:49,745 | ERROR | cost_estimator_calc_service | Params: {'servicecd': '28054', 'provideridentificationnumber': '9394609', 'placeofservice': '21', 'servicetype': 'CPT4', 'networkid': '12395', 'servicelocationnumber': '10701'}
2025-07-30 23:15:49,745 | ERROR | cost_estimator_calc_service | Exception type: <class 'google.api_core.exceptions.InvalidArgument'>
2025-07-30 23:15:49,745 | ERROR | cost_estimator_calc_service | Exception details: 400 No parameter found for binding: productcd
2025-07-30 23:15:49,745 | INFO | cost_estimator_calc_service | No rate rows found for non-standard payment methods
      INFO   127.0.0.1:54060 - "POST /costestimator/v1/rate HTTP/1.1" 200


select * from  cet_rates where provider_business_group_nbr in ('164116000')
and service_cd = '28054' and service_type_cd = 'CPT4' and product_cd = 'CAIVL' and contract_type in ('N','C')
